/* Do not modify this file!  It is created automatically by credits.sh.
   Modify credits.sh instead. */

char *aszCredits[] = {
    "Eric Augustine",
    "Steve Baedke",
    "Hans Berliner",
    "Chuck Bower",
    "Craig Campbell",
    "Tristan Colgate",
    "Bill Davidson",
    "Eric Groleau",
    "Jeff Haferman",
    "Alain Henry",
    "Jens Hoefkens",
    "Rick Janowski",
    "Tom Keith",
    "Matija Kejzar",
    "Johnny Kirk",
    "Corrin Lakeland",
    "Tim Laursen",
    "Kevin Maguire",
    "Dave Neary",
    "Peter Orum",
    "Roy Passfield",
    "Thomas Patrick",
    "Zvezdan Petkovic",
    "Petri Pitkänen",
    "Sam Pottle",
    "Jared Riley",
    "Oliver Riordan",
    "Ian Shaw",
    "Brian Sheppard",
    "Gerry Tesauro",
    "JP White",
    "Kit Woolsey",
    "Frank Worrell",
    "Michael Zehr",
    0
};
