/* Do not modify this file!  It is created automatically by credits.sh.
   Modify credits.sh instead. */

char *aszCredits[] = {
    "Kazuaki Asai",
    "Eric Augustine",
    "Steve Baedke",
    "Hans Berliner",
    "Chuck Bower",
    "Nick Bratby",
    "Craig Campbell",
    "John Chuang",
    "Tristan Colgate",
    "Olivier Croisille",
    "Ned Cross",
    "Bill Davidson",
    "Max Durbano",
    "Eric Groleau",
    "Jeff Haferman",
    "Alain Henry",
    "Jens Hoefkens",
    "Rick Janowski",
    "Nis Jorgensen",
    "Tom Keith",
    "Matija Kejzar",
    "Jonathan Kinsey",
    "Johnny Kirk",
    "Robert Konigsberg",
    "Corrin Lakeland",
    "Tim Laursen",
    "Eli Liang",
    "Kevin Maguire",
    "Thomas Meyer",
    "Achim Mueller",
    "Dave Neary",
    "Mirori Orange",
    "Peter Orum",
    "Roy Passfield",
    "Thomas Patrick",
    "Zvezdan Petkovic",
    "Nardy Pillards",
    "Petri Pitkänen",
    "Sam Pottle",
    "James Rech",
    "Jared Riley",
    "Oliver Riordan",
    "Hans-Jürgen Schäfer",
    "Jim Segrave",
    "Ian Shaw",
    "Brian Sheppard",
    "Albert Silver",
    "Peter Sochovsky",
    "Mark Spencer",
    "Maik Stiebler",
    "W. Stroop (Rob)",
    "Gerry Tesauro",
    "Jacques Thiriat",
    "Sander van Rijnswou",
    "Robert-Jan Veldhuizen",
    "JP White",
    "Kit Woolsey",
    "Frank Worrell",
    "Anders Zachrison",
    "Michael Zehr",
    0
};
