.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GNUBG 6 "March  6, 2001"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
gnubg \- play and analyse backgammon games
.SH SYNOPSIS
.B gnubg
.RI [ options ]
.RI [ saved-game-file ]
.SH DESCRIPTION
This manual page briefly documents
.B gnubg\c
, the GNU Backgammon program.
.br
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; to access this
information, type
.I info gnubg\c
\&.
.PP
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-b, \-\-no\-bearoff
Do not use bearoff database.
.TP
\fB\-d \fIDIR\fB, \-\-datadir \fIDIR
Read database and weight files from directory
.I DIR\c
\&.
.TP
\fB\-n\fR[\fIS\fR]\fB, \-\-new\-weights\fR[=\fIS\fR]
Create a new neural net of size
.I S\c
\&.
.TP
.B \-r, \-\-no\-rc
Do not read
.I .gnubgrc
and
.I .gnubgautorc
commands.
.TP
.B \-t, \-\-tty
Start on tty instead of using window system.
.TP
.B \-w, \-\-window\-system\-only
Ignore tty input when using window system.
.br
.SH SEE ALSO
.I GNU Backgammon\c
, Gary Wong.
.SH AUTHORS
Joseph Heled, Øystein Johansen, Jørn Thyssen, and Gary Wong,
with the assistance of many others <bug\-gnubg@gnu.org>.
.BR
This manual page was written by Corrin Lakeland <lakeland@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
