#!/bin/sh -e

if [ -n "$srcdir" ]; then
  dirparam="--datadir $srcdir"
else
  dirparam=""
fi

die () {
  echo "$1"
  exit 1
}

# Basic test -- could fail if there are problems with the binary.
./gnubg $dirparam -t -n -b <> /dev/null || die '--- Basic gnubg test fails.'
echo '--- Basic gnubg test succeeds.'

# Test without -b; now requires bearoff database.
./gnubg $dirparam -t -n <> /dev/null || die '--- Bearoff database test fails.'
echo '--- Bearoff database test succeeds.'

# Test without -n; now requires weights files.
./gnubg $dirparam -t <> /dev/null || die '--- Neural net weights test fails.'
echo '--- Neural net weights test succeeds.'

# Make sure an opening 31 is played correctly.
./gnubg $dirparam -t << "EOF" | grep -q sGfwATDgc/ABMA || die \
    '--- Opening move test fails.'
set player both human
new game
set turn 0
set dice 3 1
set player 0 gnubg
play
EOF
echo '--- Opening move test succeeds.'

# Play a game.
./gnubg $dirparam -t << "EOF" > /dev/null || die '--- Self-play test fails.'
set automatic game no
set player both gnubg
new game
EOF
echo '--- Self-play test succeeds.'

# Test miscellaneous commands.
./gnubg $dirparam -t << "EOF" > /dev/null || die \
    '--- Miscellaneous test fails.'
help
set player both human
show player
new game
set evaluation plies 1
eval
set rollout trials 8
set rollout truncation 8
set rollout evaluation plies 0
set rollout varredn no
rollout
EOF
echo '--- Miscellaneous test succeeds.'
