void gnubg_stock_init(void);
#define GNUBG_STOCK_ACCEPT "gnubg-stock-accept"
#define GNUBG_STOCK_DOUBLE "gnubg-stock-double"
#define GNUBG_STOCK_END_GAME "gnubg-stock-end-game"
#define GNUBG_STOCK_GO_NEXT_CMARKED "gnubg-stock-go-next-cmarked"
#define GNUBG_STOCK_GO_NEXT_GAME "gnubg-stock-go-next-game"
#define GNUBG_STOCK_GO_NEXT "gnubg-stock-go-next"
#define GNUBG_STOCK_GO_NEXT_MARKED "gnubg-stock-go-next-marked"
#define GNUBG_STOCK_GO_PREV_CMARKED "gnubg-stock-go-prev-cmarked"
#define GNUBG_STOCK_GO_PREV_GAME "gnubg-stock-go-prev-game"
#define GNUBG_STOCK_GO_PREV "gnubg-stock-go-prev"
#define GNUBG_STOCK_GO_PREV_MARKED "gnubg-stock-go-prev-marked"
#define GNUBG_STOCK_HINT "gnubg-stock-hint"
#define GNUBG_STOCK_REJECT "gnubg-stock-reject"
#define GNUBG_STOCK_RESIGN "gnubg-stock-resign"
