#define yy_create_buffer sgf_create_buffer
#define yy_delete_buffer sgf_delete_buffer
#define yy_scan_buffer sgf_scan_buffer
#define yy_scan_string sgf_scan_string
#define yy_scan_bytes sgf_scan_bytes
#define yy_flex_debug sgf_flex_debug
#define yy_init_buffer sgf_init_buffer
#define yy_flush_buffer sgf_flush_buffer
#define yy_load_buffer_state sgf_load_buffer_state
#define yy_switch_to_buffer sgf_switch_to_buffer
#define yyin sgfin
#define yyleng sgfleng
#define yylex sgflex
#define yyout sgfout
#define yyrestart sgfrestart
#define yytext sgftext

#line 19 "sgfl.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef yyconst struct yy_trans_info *yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 12
#define YY_END_OF_BUFFER 13
struct yy_trans_info
	{
	short yy_verify;
	short yy_nxt;
	};
static yyconst struct yy_trans_info yy_transition[1658] =
    {
 {   0,   0 }, {   0,1530 }, {   0,   0 }, {   0,1528 }, {   1, 520 },
 {   2, 520 }, {   3, 520 }, {   4, 520 }, {   5, 520 }, {   6, 520 },
 {   7, 520 }, {   8, 520 }, {   9, 522 }, {  10, 527 }, {  11, 522 },
 {  12, 522 }, {  13, 522 }, {  14, 520 }, {  15, 520 }, {  16, 520 },
 {  17, 520 }, {  18, 520 }, {  19, 520 }, {  20, 520 }, {  21, 520 },
 {  22, 520 }, {  23, 520 }, {  24, 520 }, {  25, 520 }, {  26, 520 },
 {  27, 520 }, {  28, 520 }, {  29, 520 }, {  30, 520 }, {  31, 520 },
 {  32, 522 }, {  33, 520 }, {  34, 520 }, {  35, 520 }, {  36, 520 },
 {  37, 520 }, {  38, 520 }, {  39, 520 }, {  40, 524 }, {  41, 524 },
 {  42, 520 }, {  43, 520 }, {  44, 520 }, {  45, 520 }, {  46, 520 },

 {  47, 520 }, {  48, 520 }, {  49, 520 }, {  50, 520 }, {  51, 520 },
 {  52, 520 }, {  53, 520 }, {  54, 520 }, {  55, 520 }, {  56, 520 },
 {  57, 520 }, {  58, 520 }, {  59, 524 }, {  60, 520 }, {  61, 520 },
 {  62, 520 }, {  63, 520 }, {  64, 520 }, {  65, 529 }, {  66, 529 },
 {  67, 529 }, {  68, 529 }, {  69, 529 }, {  70, 529 }, {  71, 529 },
 {  72, 529 }, {  73, 529 }, {  74, 529 }, {  75, 529 }, {  76, 529 },
 {  77, 529 }, {  78, 529 }, {  79, 529 }, {  80, 529 }, {  81, 529 },
 {  82, 529 }, {  83, 529 }, {  84, 529 }, {  85, 529 }, {  86, 529 },
 {  87, 529 }, {  88, 529 }, {  89, 529 }, {  90, 529 }, {  91, 542 },
 {  92, 520 }, {  93, 520 }, {  94, 520 }, {  95, 520 }, {  96, 520 },

 {  97, 587 }, {  98, 587 }, {  99, 587 }, { 100, 587 }, { 101, 587 },
 { 102, 587 }, { 103, 587 }, { 104, 587 }, { 105, 587 }, { 106, 587 },
 { 107, 587 }, { 108, 587 }, { 109, 587 }, { 110, 587 }, { 111, 587 },
 { 112, 587 }, { 113, 587 }, { 114, 587 }, { 115, 587 }, { 116, 587 },
 { 117, 587 }, { 118, 587 }, { 119, 587 }, { 120, 587 }, { 121, 587 },
 { 122, 587 }, { 123, 520 }, { 124, 520 }, { 125, 520 }, { 126, 520 },
 { 127, 520 }, { 128, 520 }, {   0,   0 }, {   0,1398 }, {   1, 390 },
 {   2, 390 }, {   3, 390 }, {   4, 390 }, {   5, 390 }, {   6, 390 },
 {   7, 390 }, {   8, 390 }, {   9, 392 }, {  10, 397 }, {  11, 392 },
 {  12, 392 }, {  13, 392 }, {  14, 390 }, {  15, 390 }, {  16, 390 },

 {  17, 390 }, {  18, 390 }, {  19, 390 }, {  20, 390 }, {  21, 390 },
 {  22, 390 }, {  23, 390 }, {  24, 390 }, {  25, 390 }, {  26, 390 },
 {  27, 390 }, {  28, 390 }, {  29, 390 }, {  30, 390 }, {  31, 390 },
 {  32, 392 }, {  33, 390 }, {  34, 390 }, {  35, 390 }, {  36, 390 },
 {  37, 390 }, {  38, 390 }, {  39, 390 }, {  40, 394 }, {  41, 394 },
 {  42, 390 }, {  43, 390 }, {  44, 390 }, {  45, 390 }, {  46, 390 },
 {  47, 390 }, {  48, 390 }, {  49, 390 }, {  50, 390 }, {  51, 390 },
 {  52, 390 }, {  53, 390 }, {  54, 390 }, {  55, 390 }, {  56, 390 },
 {  57, 390 }, {  58, 390 }, {  59, 394 }, {  60, 390 }, {  61, 390 },
 {  62, 390 }, {  63, 390 }, {  64, 390 }, {  65, 399 }, {  66, 399 },

 {  67, 399 }, {  68, 399 }, {  69, 399 }, {  70, 399 }, {  71, 399 },
 {  72, 399 }, {  73, 399 }, {  74, 399 }, {  75, 399 }, {  76, 399 },
 {  77, 399 }, {  78, 399 }, {  79, 399 }, {  80, 399 }, {  81, 399 },
 {  82, 399 }, {  83, 399 }, {  84, 399 }, {  85, 399 }, {  86, 399 },
 {  87, 399 }, {  88, 399 }, {  89, 399 }, {  90, 399 }, {  91, 412 },
 {  92, 390 }, {  93, 390 }, {  94, 390 }, {  95, 390 }, {  96, 390 },
 {  97, 457 }, {  98, 457 }, {  99, 457 }, { 100, 457 }, { 101, 457 },
 { 102, 457 }, { 103, 457 }, { 104, 457 }, { 105, 457 }, { 106, 457 },
 { 107, 457 }, { 108, 457 }, { 109, 457 }, { 110, 457 }, { 111, 457 },
 { 112, 457 }, { 113, 457 }, { 114, 457 }, { 115, 457 }, { 116, 457 },

 { 117, 457 }, { 118, 457 }, { 119, 457 }, { 120, 457 }, { 121, 457 },
 { 122, 457 }, { 123, 390 }, { 124, 390 }, { 125, 390 }, { 126, 390 },
 { 127, 390 }, { 128, 390 }, {   0,   0 }, {   0,1268 }, {   1, 451 },
 {   2, 451 }, {   3, 451 }, {   4, 451 }, {   5, 451 }, {   6, 451 },
 {   7, 451 }, {   8, 451 }, {   9, 451 }, {  10, 451 }, {  11, 451 },
 {  12, 451 }, {  13, 451 }, {  14, 451 }, {  15, 451 }, {  16, 451 },
 {  17, 451 }, {  18, 451 }, {  19, 451 }, {  20, 451 }, {  21, 451 },
 {  22, 451 }, {  23, 451 }, {  24, 451 }, {  25, 451 }, {  26, 451 },
 {  27, 451 }, {  28, 451 }, {  29, 451 }, {  30, 451 }, {  31, 451 },
 {  32, 451 }, {  33, 451 }, {  34, 451 }, {  35, 451 }, {  36, 451 },

 {  37, 451 }, {  38, 451 }, {  39, 451 }, {  40, 451 }, {  41, 451 },
 {  42, 451 }, {  43, 451 }, {  44, 451 }, {  45, 451 }, {  46, 451 },
 {  47, 451 }, {  48, 451 }, {  49, 451 }, {  50, 451 }, {  51, 451 },
 {  52, 451 }, {  53, 451 }, {  54, 451 }, {  55, 451 }, {  56, 451 },
 {  57, 451 }, {  58, 451 }, {  59, 451 }, {  60, 451 }, {  61, 451 },
 {  62, 451 }, {  63, 451 }, {  64, 451 }, {  65, 451 }, {  66, 451 },
 {  67, 451 }, {  68, 451 }, {  69, 451 }, {  70, 451 }, {  71, 451 },
 {  72, 451 }, {  73, 451 }, {  74, 451 }, {  75, 451 }, {  76, 451 },
 {  77, 451 }, {  78, 451 }, {  79, 451 }, {  80, 451 }, {  81, 451 },
 {  82, 451 }, {  83, 451 }, {  84, 451 }, {  85, 451 }, {  86, 451 },

 {  87, 451 }, {  88, 451 }, {  89, 451 }, {  90, 451 }, {  91, 451 },
 {  92, 581 }, {  93, 284 }, {  94, 451 }, {  95, 451 }, {  96, 451 },
 {  97, 451 }, {  98, 451 }, {  99, 451 }, { 100, 451 }, { 101, 451 },
 { 102, 451 }, { 103, 451 }, { 104, 451 }, { 105, 451 }, { 106, 451 },
 { 107, 451 }, { 108, 451 }, { 109, 451 }, { 110, 451 }, { 111, 451 },
 { 112, 451 }, { 113, 451 }, { 114, 451 }, { 115, 451 }, { 116, 451 },
 { 117, 451 }, { 118, 451 }, { 119, 451 }, { 120, 451 }, { 121, 451 },
 { 122, 451 }, { 123, 451 }, { 124, 451 }, { 125, 451 }, { 126, 451 },
 { 127, 451 }, { 128, 451 }, {   0,   0 }, {   0,1138 }, {   1, 321 },
 {   2, 321 }, {   3, 321 }, {   4, 321 }, {   5, 321 }, {   6, 321 },

 {   7, 321 }, {   8, 321 }, {   9, 321 }, {  10, 321 }, {  11, 321 },
 {  12, 321 }, {  13, 321 }, {  14, 321 }, {  15, 321 }, {  16, 321 },
 {  17, 321 }, {  18, 321 }, {  19, 321 }, {  20, 321 }, {  21, 321 },
 {  22, 321 }, {  23, 321 }, {  24, 321 }, {  25, 321 }, {  26, 321 },
 {  27, 321 }, {  28, 321 }, {  29, 321 }, {  30, 321 }, {  31, 321 },
 {  32, 321 }, {  33, 321 }, {  34, 321 }, {  35, 321 }, {  36, 321 },
 {  37, 321 }, {  38, 321 }, {  39, 321 }, {  40, 321 }, {  41, 321 },
 {  42, 321 }, {  43, 321 }, {  44, 321 }, {  45, 321 }, {  46, 321 },
 {  47, 321 }, {  48, 321 }, {  49, 321 }, {  50, 321 }, {  51, 321 },
 {  52, 321 }, {  53, 321 }, {  54, 321 }, {  55, 321 }, {  56, 321 },

 {  57, 321 }, {  58, 321 }, {  59, 321 }, {  60, 321 }, {  61, 321 },
 {  62, 321 }, {  63, 321 }, {  64, 321 }, {  65, 321 }, {  66, 321 },
 {  67, 321 }, {  68, 321 }, {  69, 321 }, {  70, 321 }, {  71, 321 },
 {  72, 321 }, {  73, 321 }, {  74, 321 }, {  75, 321 }, {  76, 321 },
 {  77, 321 }, {  78, 321 }, {  79, 321 }, {  80, 321 }, {  81, 321 },
 {  82, 321 }, {  83, 321 }, {  84, 321 }, {  85, 321 }, {  86, 321 },
 {  87, 321 }, {  88, 321 }, {  89, 321 }, {  90, 321 }, {  91, 321 },
 {  92, 451 }, {  93, 154 }, {  94, 321 }, {  95, 321 }, {  96, 321 },
 {  97, 321 }, {  98, 321 }, {  99, 321 }, { 100, 321 }, { 101, 321 },
 { 102, 321 }, { 103, 321 }, { 104, 321 }, { 105, 321 }, { 106, 321 },

 { 107, 321 }, { 108, 321 }, { 109, 321 }, { 110, 321 }, { 111, 321 },
 { 112, 321 }, { 113, 321 }, { 114, 321 }, { 115, 321 }, { 116, 321 },
 { 117, 321 }, { 118, 321 }, { 119, 321 }, { 120, 321 }, { 121, 321 },
 { 122, 321 }, { 123, 321 }, { 124, 321 }, { 125, 321 }, { 126, 321 },
 { 127, 321 }, { 128, 321 }, {   0,   6 }, {   0,1008 }, {   0,   1 },
 {   0,1006 }, {   0,   2 }, {   0,1004 }, {   0,   0 }, {   0,   1 },
 {   0,1001 }, {   0,   3 }, {   0, 999 }, {   0,   0 }, {   9, 449 },
 {  10, 449 }, {  11, 449 }, {  12, 449 }, {  13, 449 }, {   9, 444 },
 {  10, 444 }, {  11, 444 }, {  12, 444 }, {  13, 444 }, {   0,   5 },
 {   0, 986 }, {   0,   9 }, {   0, 984 }, {   0,  11 }, {   0, 982 },

 {   0,   8 }, {   0, 980 }, {   0,   7 }, {   0, 978 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  32, 449 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  32, 444 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   4 },
 {   0, 941 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  65, 444 }, {  66, 444 }, {  67, 444 },

 {  68, 444 }, {  69, 444 }, {  70, 444 }, {  71, 444 }, {  72, 444 },
 {  73, 444 }, {  74, 444 }, {  75, 444 }, {  76, 444 }, {  77, 444 },
 {  78, 444 }, {  79, 444 }, {  80, 444 }, {  81, 444 }, {  82, 444 },
 {  83, 444 }, {  84, 444 }, {  85, 444 }, {  86, 444 }, {  87, 444 },
 {  88, 444 }, {  89, 444 }, {  90, 444 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {  97, 502 },
 {  98, 502 }, {  99, 502 }, { 100, 502 }, { 101, 502 }, { 102, 502 },
 { 103, 502 }, { 104, 502 }, { 105, 502 }, { 106, 502 }, { 107, 502 },
 { 108, 502 }, { 109, 502 }, { 110, 502 }, { 111, 502 }, { 112, 502 },
 { 113, 502 }, { 114, 502 }, { 115, 502 }, { 116, 502 }, { 117, 502 },

 { 118, 502 }, { 119, 502 }, { 120, 502 }, { 121, 502 }, { 122, 502 },
 {  65, 536 }, {  66, 536 }, {  67, 536 }, {  68, 536 }, {  69, 536 },
 {  70, 536 }, {  71, 536 }, {  72, 536 }, {  73, 536 }, {  74, 536 },
 {  75, 536 }, {  76, 536 }, {  77, 536 }, {  78, 536 }, {  79, 536 },
 {  80, 536 }, {  81, 536 }, {  82, 536 }, {  83, 536 }, {  84, 536 },
 {  85, 536 }, {  86, 536 }, {  87, 536 }, {  88, 536 }, {  89, 536 },
 {  90, 536 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {  97, 594 }, {  98, 594 }, {  99, 594 },
 { 100, 594 }, { 101, 594 }, { 102, 594 }, { 103, 594 }, { 104, 594 },
 { 105, 594 }, { 106, 594 }, { 107, 594 }, { 108, 594 }, { 109, 594 },

 { 110, 594 }, { 111, 594 }, { 112, 594 }, { 113, 594 }, { 114, 594 },
 { 115, 594 }, { 116, 594 }, { 117, 594 }, { 118, 594 }, { 119, 594 },
 { 120, 594 }, { 121, 594 }, { 122, 594 }, {   0,  10 }, {   0, 817 },
 {   1, 594 }, {   2, 594 }, {   3, 594 }, {   4, 594 }, {   5, 594 },
 {   6, 594 }, {   7, 594 }, {   8, 594 }, {   9, 594 }, {  10, 594 },
 {  11, 594 }, {  12, 594 }, {  13, 594 }, {  14, 594 }, {  15, 594 },
 {  16, 594 }, {  17, 594 }, {  18, 594 }, {  19, 594 }, {  20, 594 },
 {  21, 594 }, {  22, 594 }, {  23, 594 }, {  24, 594 }, {  25, 594 },
 {  26, 594 }, {  27, 594 }, {  28, 594 }, {  29, 594 }, {  30, 594 },
 {  31, 594 }, {  32, 594 }, {  33, 594 }, {  34, 594 }, {  35, 594 },

 {  36, 594 }, {  37, 594 }, {  38, 594 }, {  39, 594 }, {  40, 594 },
 {  41, 594 }, {  42, 594 }, {  43, 594 }, {  44, 594 }, {  45, 594 },
 {  46, 594 }, {  47, 594 }, {  48, 594 }, {  49, 594 }, {  50, 594 },
 {  51, 594 }, {  52, 594 }, {  53, 594 }, {  54, 594 }, {  55, 594 },
 {  56, 594 }, {  57, 594 }, {  58, 594 }, {  59, 594 }, {  60, 594 },
 {  61, 594 }, {  62, 594 }, {  63, 594 }, {  64, 594 }, {  65, 594 },
 {  66, 594 }, {  67, 594 }, {  68, 594 }, {  69, 594 }, {  70, 594 },
 {  71, 594 }, {  72, 594 }, {  73, 594 }, {  74, 594 }, {  75, 594 },
 {  76, 594 }, {  77, 594 }, {  78, 594 }, {  79, 594 }, {  80, 594 },
 {  81, 594 }, {  82, 594 }, {  83, 594 }, {  84, 594 }, {  85, 594 },

 {  86, 594 }, {  87, 594 }, {  88, 594 }, {  89, 594 }, {  90, 594 },
 {  91, 594 }, {   0,   0 }, {   0,   0 }, {  94, 594 }, {  95, 594 },
 {  96, 594 }, {  97, 594 }, {  98, 594 }, {  99, 594 }, { 100, 594 },
 { 101, 594 }, { 102, 594 }, { 103, 594 }, { 104, 594 }, { 105, 594 },
 { 106, 594 }, { 107, 594 }, { 108, 594 }, { 109, 594 }, { 110, 594 },
 { 111, 594 }, { 112, 594 }, { 113, 594 }, { 114, 594 }, { 115, 594 },
 { 116, 594 }, { 117, 594 }, { 118, 594 }, { 119, 594 }, { 120, 594 },
 { 121, 594 }, { 122, 594 }, { 123, 594 }, { 124, 594 }, { 125, 594 },
 { 126, 594 }, { 127, 594 }, { 128, 594 }, {   0,  11 }, {   0, 687 },
 {   1,-295 }, {   2,-295 }, {   3,-295 }, {   4,-295 }, {   5,-295 },

 {   6,-295 }, {   7,-295 }, {   8,-295 }, {   9,-295 }, {  10,-293 },
 {  11,-295 }, {  12,-295 }, {  13,-295 }, {  14,-295 }, {  15,-295 },
 {  16,-295 }, {  17,-295 }, {  18,-295 }, {  19,-295 }, {  20,-295 },
 {  21,-295 }, {  22,-295 }, {  23,-295 }, {  24,-295 }, {  25,-295 },
 {  26,-295 }, {  27,-295 }, {  28,-295 }, {  29,-295 }, {  30,-295 },
 {  31,-295 }, {  32,-295 }, {  33,-295 }, {  34,-295 }, {  35,-295 },
 {  36,-295 }, {  37,-295 }, {  38,-295 }, {  39,-295 }, {  40,-295 },
 {  41,-295 }, {  42,-295 }, {  43,-295 }, {  44,-295 }, {  45,-295 },
 {  46,-295 }, {  47,-295 }, {  48,-295 }, {  49,-295 }, {  50,-295 },
 {  51,-295 }, {  52,-295 }, {  53,-295 }, {  54,-295 }, {  55,-295 },

 {  56,-295 }, {  57,-295 }, {  58,-295 }, {  59,-295 }, {  60,-295 },
 {  61,-295 }, {  62,-295 }, {  63,-295 }, {  64,-295 }, {  65,-295 },
 {  66,-295 }, {  67,-295 }, {  68,-295 }, {  69,-295 }, {  70,-295 },
 {  71,-295 }, {  72,-295 }, {  73,-295 }, {  74,-295 }, {  75,-295 },
 {  76,-295 }, {  77,-295 }, {  78,-295 }, {  79,-295 }, {  80,-295 },
 {  81,-295 }, {  82,-295 }, {  83,-295 }, {  84,-295 }, {  85,-295 },
 {  86,-295 }, {  87,-295 }, {  88,-295 }, {  89,-295 }, {  90,-295 },
 {  91,-295 }, {  92,-295 }, {  93,-291 }, {  94,-295 }, {  95,-295 },
 {  96,-295 }, {  97,-295 }, {  98,-295 }, {  99,-295 }, { 100,-295 },
 { 101,-295 }, { 102,-295 }, { 103,-295 }, { 104,-295 }, { 105,-295 },

 { 106,-295 }, { 107,-295 }, { 108,-295 }, { 109,-295 }, { 110,-295 },
 { 111,-295 }, { 112,-295 }, { 113,-295 }, { 114,-295 }, { 115,-295 },
 { 116,-295 }, { 117,-295 }, { 118,-295 }, { 119,-295 }, { 120,-295 },
 { 121,-295 }, { 122,-295 }, { 123,-295 }, { 124,-295 }, { 125,-295 },
 { 126,-295 }, { 127,-295 }, { 128,-295 }, {   0,   1 }, {   0, 557 },
 {   0,   3 }, {   0, 555 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   9,   0 }, {  10,   0 },
 {  11,   0 }, {  12,   0 }, {  13,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  32,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   3 }, {   0, 497 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  97, 425 }, {  98, 425 },
 {  99, 425 }, { 100, 425 }, { 101, 425 }, { 102, 425 }, { 103, 425 },
 { 104, 425 }, { 105, 425 }, { 106, 425 }, { 107, 425 }, { 108, 425 },
 { 109, 425 }, { 110, 425 }, { 111, 425 }, { 112, 425 }, { 113, 425 },
 { 114, 425 }, { 115, 425 }, { 116, 425 }, { 117, 425 }, { 118, 425 },
 { 119, 425 }, { 120, 425 }, { 121, 425 }, { 122, 425 }, {  65, -58 },

 {  66, -58 }, {  67, -58 }, {  68, -58 }, {  69, -58 }, {  70, -58 },
 {  71, -58 }, {  72, -58 }, {  73, -58 }, {  74, -58 }, {  75, -58 },
 {  76, -58 }, {  77, -58 }, {  78, -58 }, {  79, -58 }, {  80, -58 },
 {  81, -58 }, {  82, -58 }, {  83, -58 }, {  84, -58 }, {  85, -58 },
 {  86, -58 }, {  87, -58 }, {  88, -58 }, {  89, -58 }, {  90, -58 },
 {   0,   3 }, {   0, 405 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  97,   0 }, {  98,   0 }, {  99,   0 }, { 100,   0 },
 { 101,   0 }, { 102,   0 }, { 103,   0 }, { 104,   0 }, { 105,   0 },
 { 106,   0 }, { 107,   0 }, { 108,   0 }, { 109,   0 }, { 110,   0 },
 { 111,   0 }, { 112,   0 }, { 113,   0 }, { 114,   0 }, { 115,   0 },

 { 116,   0 }, { 117,   0 }, { 118,   0 }, { 119,   0 }, { 120,   0 },
 { 121,   0 }, { 122,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   4 }, {   0, 347 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  65,-150 }, {  66,-150 }, {  67,-150 }, {  68,-150 },
 {  69,-150 }, {  70,-150 }, {  71,-150 }, {  72,-150 }, {  73,-150 },

 {  74,-150 }, {  75,-150 }, {  76,-150 }, {  77,-150 }, {  78,-150 },
 {  79,-150 }, {  80,-150 }, {  81,-150 }, {  82,-150 }, {  83,-150 },
 {  84,-150 }, {  85,-150 }, {  86,-150 }, {  87,-150 }, {  88,-150 },
 {  89,-150 }, {  90,-150 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  97, -92 }, {  98, -92 },
 {  99, -92 }, { 100, -92 }, { 101, -92 }, { 102, -92 }, { 103, -92 },
 { 104, -92 }, { 105, -92 }, { 106, -92 }, { 107, -92 }, { 108, -92 },
 { 109, -92 }, { 110, -92 }, { 111, -92 }, { 112, -92 }, { 113, -92 },
 { 114, -92 }, { 115, -92 }, { 116, -92 }, { 117, -92 }, { 118, -92 },
 { 119, -92 }, { 120, -92 }, { 121, -92 }, { 122, -92 }, {  65, -58 },

 {  66, -58 }, {  67, -58 }, {  68, -58 }, {  69, -58 }, {  70, -58 },
 {  71, -58 }, {  72, -58 }, {  73, -58 }, {  74, -58 }, {  75, -58 },
 {  76, -58 }, {  77, -58 }, {  78, -58 }, {  79, -58 }, {  80, -58 },
 {  81, -58 }, {  82, -58 }, {  83, -58 }, {  84, -58 }, {  85, -58 },
 {  86, -58 }, {  87, -58 }, {  88, -58 }, {  89, -58 }, {  90, -58 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {  97,   0 }, {  98,   0 }, {  99,   0 }, { 100,   0 },
 { 101,   0 }, { 102,   0 }, { 103,   0 }, { 104,   0 }, { 105,   0 },
 { 106,   0 }, { 107,   0 }, { 108,   0 }, { 109,   0 }, { 110,   0 },
 { 111,   0 }, { 112,   0 }, { 113,   0 }, { 114,   0 }, { 115,   0 },

 { 116,   0 }, { 117,   0 }, { 118,   0 }, { 119,   0 }, { 120,   0 },
 { 121,   0 }, { 122,   0 }, {   0,  10 }, {   0, 223 }, {   1,   0 },
 {   2,   0 }, {   3,   0 }, {   4,   0 }, {   5,   0 }, {   6,   0 },
 {   7,   0 }, {   8,   0 }, {   9,   0 }, {  10,   0 }, {  11,   0 },
 {  12,   0 }, {  13,   0 }, {  14,   0 }, {  15,   0 }, {  16,   0 },
 {  17,   0 }, {  18,   0 }, {  19,   0 }, {  20,   0 }, {  21,   0 },
 {  22,   0 }, {  23,   0 }, {  24,   0 }, {  25,   0 }, {  26,   0 },
 {  27,   0 }, {  28,   0 }, {  29,   0 }, {  30,   0 }, {  31,   0 },
 {  32,   0 }, {  33,   0 }, {  34,   0 }, {  35,   0 }, {  36,   0 },
 {  37,   0 }, {  38,   0 }, {  39,   0 }, {  40,   0 }, {  41,   0 },

 {  42,   0 }, {  43,   0 }, {  44,   0 }, {  45,   0 }, {  46,   0 },
 {  47,   0 }, {  48,   0 }, {  49,   0 }, {  50,   0 }, {  51,   0 },
 {  52,   0 }, {  53,   0 }, {  54,   0 }, {  55,   0 }, {  56,   0 },
 {  57,   0 }, {  58,   0 }, {  59,   0 }, {  60,   0 }, {  61,   0 },
 {  62,   0 }, {  63,   0 }, {  64,   0 }, {  65,   0 }, {  66,   0 },
 {  67,   0 }, {  68,   0 }, {  69,   0 }, {  70,   0 }, {  71,   0 },
 {  72,   0 }, {  73,   0 }, {  74,   0 }, {  75,   0 }, {  76,   0 },
 {  77,   0 }, {  78,   0 }, {  79,   0 }, {  80,   0 }, {  81,   0 },
 {  82,   0 }, {  83,   0 }, {  84,   0 }, {  85,   0 }, {  86,   0 },
 {  87,   0 }, {  88,   0 }, {  89,   0 }, {  90,   0 }, {  91,   0 },

 {   0,   3 }, {   0, 130 }, {  94,   0 }, {  95,   0 }, {  96,   0 },
 {  97,   0 }, {  98,   0 }, {  99,   0 }, { 100,   0 }, { 101,   0 },
 { 102,   0 }, { 103,   0 }, { 104,   0 }, { 105,   0 }, { 106,   0 },
 { 107,   0 }, { 108,   0 }, { 109,   0 }, { 110,   0 }, { 111,   0 },
 { 112,   0 }, { 113,   0 }, { 114,   0 }, { 115,   0 }, { 116,   0 },
 { 117,   0 }, { 118,   0 }, { 119,   0 }, { 120,   0 }, { 121,   0 },
 { 122,   0 }, { 123,   0 }, { 124,   0 }, { 125,   0 }, { 126,   0 },
 { 127,   0 }, { 128,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },

 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {  97,   0 }, {  98,   0 },

 {  99,   0 }, { 100,   0 }, { 101,   0 }, { 102,   0 }, { 103,   0 },
 { 104,   0 }, { 105,   0 }, { 106,   0 }, { 107,   0 }, { 108,   0 },
 { 109,   0 }, { 110,   0 }, { 111,   0 }, { 112,   0 }, { 113,   0 },
 { 114,   0 }, { 115,   0 }, { 116,   0 }, { 117,   0 }, { 118,   0 },
 { 119,   0 }, { 120,   0 }, { 121,   0 }, { 122,   0 }, {   0,   0 },
 {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 }, {   0,   0 },
 { 129,  13 }, {   1,   0 },    };

static yyconst struct yy_trans_info *yy_start_state_list[5] =
    {
    &yy_transition[1],
    &yy_transition[3],
    &yy_transition[133],
    &yy_transition[263],
    &yy_transition[393],


    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sgf.l"
#define INITIAL 0
/*
 * sgf.l
 *
 * by Gary Wong <gtw@gnu.org>, 2000.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * $Id$
 */
#line 23 "sgf.l"
#include <ctype.h>
#include <list.h>
#include <string.h>

#include "sgf.h"
#include "sgfp.h"

extern int _SGFWarning( char * );

static int error( char *s ) {

    /* refer to yy_fatal_error, to shut up the compiler */
    (void) yy_fatal_error;

    if( SGFErrorHandler )
	SGFErrorHandler( s, 0 );
    else
	fprintf( stderr, "%s\n", s );
    
    return 0;
}

#define YY_FATAL_ERROR(m) error(m)
#define YY_NO_INPUT 1
#define YY_NO_UNPUT 1
#define YY_NO_SCAN_BUFFER 1
#define YY_NO_SCAN_BYTES 1
#define YY_NO_SCAN_STRING 1
#define value 1

#line 726 "sgfl.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 62 "sgf.l"


#line 880 "sgfl.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start_state_list[yy_start];
yy_match:
		{
		register yyconst struct yy_trans_info *yy_trans_info;

		register YY_CHAR yy_c;

		for ( yy_c = YY_SC_TO_UI(*yy_cp);
		      (yy_trans_info = &yy_current_state[(unsigned int) yy_c])->
		yy_verify == yy_c;
		      yy_c = YY_SC_TO_UI(*++yy_cp) )
			yy_current_state += yy_trans_info->yy_nxt;
		}

yy_find_action:
		yy_act = yy_current_state[-1].yy_nxt;

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 64 "sgf.l"
/* ignore */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "sgf.l"
return *yytext;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "sgf.l"
{
			    char *pch;

			    sgflval.ach[ 1 ] = 0;

			    for( pch = yytext; *pch; pch++ )
			        if( isupper( *pch ) ) {
				    sgflval.ach[ 0 ] = *pch;    
				    break;
				}

			    for( pch++; *pch; pch++ )
			        if( isupper( *pch ) ) {
				    sgflval.ach[ 1 ] = *pch;
				    break;
				}

			    return PROPERTY;
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "sgf.l"
/* ignore -- this rule avoids making flex back up */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 86 "sgf.l"
BEGIN(value); return '[';
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 87 "sgf.l"
{ error( "illegal character in SGF file" ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "sgf.l"
{ sgflval.pch = strdup( "]" ); return VALUETEXT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "sgf.l"
/* ignore */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "sgf.l"
BEGIN(INITIAL); return ']';
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "sgf.l"
{ sgflval.pch = strdup( yytext ); return VALUETEXT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "sgf.l"
{ sgflval.pch = strdup( yytext ); return VALUETEXT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 95 "sgf.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1021 "sgfl.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(value):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start_state_list[yy_start];

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		yy_current_state += yy_current_state[(*yy_cp ? YY_SC_TO_UI(*yy_cp) : 128)].yy_nxt;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register int yy_c = 128;
	register yyconst struct yy_trans_info *yy_trans_info;

	yy_trans_info = &yy_current_state[(unsigned int) yy_c];
	yy_current_state += yy_trans_info->yy_nxt;
	yy_is_jam = (yy_trans_info->yy_verify != yy_c);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 95 "sgf.l"

