@node Frequently Asked Questions
@chapter Frequently Asked Questions
@cindex frequently asked questions
@cindex FAQ

This chapter documents the most frequently asked questions. Sources are the
newsgroup @uref{news:rec.games.backgammon,, rec.games.backgammon}, the
@uref{mailto:bug-gnubg@@gnu.org,, @gnubg{}-mailinglist} and the
@uref{http://www.gammonline.com,, bulletin board of Kit Woolseys online
magazine @emph{GammOnLine}}.

@menu
* General questions::
* Installation questions::
* @gnubg{} startup questions::
* Backgammon playing questions::
* Settings questions::
* Analysis questions::
* Database questions::
* Abbreviations::
@end menu

@node General questions
@section General questions

@menu
* What is GNU Backgammon?::
* What operating systems are supported?::
* Where do I get it?::
* What do I have to pay for GNU Backgammon?::
* This GNU stuff sounds interesting.::
* I want to learn more about backgammon.::
* Though I really read all the documentation I still have questions.::
* I want to make a few proposals. I have new ideas.::
* This F.A.Q. is full of typos and in bad English.::
@end menu


@node What is GNU Backgammon?    
@subsection What is GNU Backgammon?

GNU Backgammon (@gnubg{}) is for playing and analysing backgammon
positions, games and matches. It's based on a neural network. Though it
already plays on a very high level, it's still work in progress. You may
play GNU Backgammon using the command line or a graphical interface
(based on GTK+).

@node What operating systems are supported?
@subsection What operating systems are supported?

Currently GNU Backgammon is actually designed for @emph{GNU/Linux}. It
also compiles and (hopefully) runs under @emph{*BSD, IRIX, Solaris} and
@emph{True64 Unix}. Last but not least there are frequently binaries for
@emph{MS Windows} and @emph{MS DOS}. Porting to @emph{MacOS} is planned
but not yet released. When you successfully port GNU Backgammon to other
operating systems you are welcome to give us a note at
@uref{bug-gnubg@@gnu.org}.

@node Where do I get it?
@subsection Where do I get it?

The official website is
@uref{http://www.gnu.org/software/gnubg/gnubg.html}. You can get daily
snapshots at @uref{ftp://alpha.gnu.org/gnu/gnubg/snapshots/}. @emph{MS
Windows} binaries are available at
@uref{http://home.online.no/%7Eoeysteij/}. @emph{GNU/Linux}-Rpm's are
(hopefully) soon available at @uref{http://mole.dnsalias.org/~acepoint/,,
acepoint's home}.


@node What do I have to pay for GNU Backgammon?
@subsection What do I have to pay for GNU Backgammon?

GNU Backgammon is @emph{Open Source Software} and belongs to
the @emph{GNU Project}. You may download it for free. For more
information see the @uref{http://www.gnu.org/licenses/gpl.html,, GNU
General Public License}. But be aware that GNU Backgammon is not
@emph{public domain software} or @emph{shareware} as you perhaps know
from @emph{MS Windows}.

@node This GNU stuff sounds interesting.
@subsection This GNU stuff sounds interesting.

Take a look at the @uref{http://www.gnu.org,, GNU's homepage}.

@node I want to learn more about backgammon.
@subsection I want to learn more about backgammon.

A good place to start is @uref{http://www.bkgm.com,, The Backgammon
Galore}. For an extensive link collection go to
@uref{http://www.chicagopoint.com/links.html,, Gammon-links}.

@node Though I really read all the documentation I still have questions.
@subsection Though I really read all the documentation I still have questions.

Send an email to the @uref{mailto:bug-gnubg@@gnu.org,,
@gnubg{}-mailinglist}. If it is a bug, be sure to include a reference of
your operating system, the version of @gnubg{} you use and possible
error messages you get. Try to describe exactly what happens, before the
error occurs.

@node I want to make a few proposals. I have new ideas.
@subsection I want to make a few proposals. I have new ideas.

You're welcome! Send an email with your suggestions to 
@uref{mailto:bug-gnubg@@gnu.org,, @gnubg{}-mailinglist}.

@node This F.A.Q. is full of typos and in bad English.
@subsection This F.A.Q. is full of typos and in bad English.

Probably you are right. But you are cordially invited to send
corrections to @email{acepoint@@deltacity.net}. And keep the following
quote in mind ;-):

@cite{Documentation is like sex: when it is good, it is very, very good,
and when it is bad, it is better than nothing.}

@cite{[ Dick Brandon ]}

@node Installation questions
@section Installation questions

@menu
* Where do I find an installable version for my operating system?::
* Do I need some other software to run GNU Backgammon?::
* I want to install a newer version.::
* I would like to compile it from the source code.::
* What software do I need for compiling under @emph{GNU/Linux}?::
* What software do I need for compiling under @emph{MS Windows}?::
* It does not compile.::
@end menu

@node Where do I find an installable version for my operating system?
@subsection Where do I find an installable version for my operating system?

For @emph{MS Windows} go to @uref{http://home.online.no/%7Eoeysteij/,, this
place}. @emph{GNU/Linux}-Rpm's are (hopefully) soon available at
@uref{http://mole.dnsalias.org/~acepoint/,, acepoint's home}.

@node Do I need some other software to run GNU Backgammon?
@subsection Do I need some other software to run GNU Backgammon?

No. All stuff you need is included in the binaries.

@node I want to install a newer version.
@subsection  I want to install a newer version.

If you are using a @emph{MS Windows} operating system make a copy of
either @file{.gnubgrc} or @file{.gnubgautorc} and
@file{.gnubgmenurc}. You will find them either in @file{c:} or the home
directory of your GNU Backgammon (for instance: @file{c:\program
files\gnubg\}). After you have installed the new version, copy them
back.

 If you are working with @emph{GNU/Linux} these files are
probably in your home directory (@file{~/}). They won't be overwritten
by installing a new version of GNU Backgammon. But it's always a good
idea to have a backup of them. 

@node I would like to compile it from the source code.
@subsection I would like to compile it from the source code.

@ifnottex
Good luck to you! Download the source code and make sure to read one of the
following two items: @ref{What software do I need for compiling under
@emph{GNU/Linux}?}, @ref{What software do I need for compiling under
@emph{MS Windows}?}.
@end ifnottex

@iftex
Good luck to you! Download the source code and make sure to read one of the
following two items: What software do I need for compiling under
@emph{GNU/Linux}, What software do I need for compiling under @emph{MS
Windows}.
@end iftex

@node What software do I need for compiling under @emph{GNU/Linux}?
@subsection What software do I need for compiling under @emph{GNU/Linux}?

Depending on the distribution you are working with:

@itemize
@item @uref{ftp://alpha.gnu.org/gnu/gnubg/snapshots/,, GNU Backgammon
snapshots}
@item a @emph{"C-"}compiler
@item autoconf and automake
@item xdevel (for the graphical interface)
@item gtk+ >= 1.2 (for the graphical interface)
@item gtk+-devel
@item guile (optional, for invoking your own macros)
@item guile-devel
@item gdbm (optional, for using your own databases)
@item gdbm-devel
@end itemize

Unpack the GNU Backgammon snapshots and follow the instructions of the
file @file{INSTALL}.

@node What software do I need for compiling under @emph{MS Windows}?
@subsection  What software do I need for compiling under @emph{MS Windows}?

Nardy Pillards has published a fine instruction guide at
@uref{http://users.skynet.be/bk228456/GNUBgW.htm,, Windows-Build}.
Go to this page and follow the steps shown there.

@node It does not compile.
@subsection It does not compile.

@ifnottex
Check that you have installed all necessary development packages. For

@emph{GNU/Linux}:@ref{What software do I need for compiling under
@emph{GNU/Linux}?},

and for 

@emph{MS Windows}:@ref{What software do I need for compiling under
@emph{MS Windows}?} should be listed all you probably want.
@end ifnottex

@iftex
Check that you have installed all necessary development packages. For

@emph{GNU/Linux}: What software do I need for compiling under
@emph{GNU/Linux},

and for 

@emph{MS Windows}: What software do I need for compiling under
@emph{MS Windows} should be listed all you probably want.
@end iftex

Look for warnings or errors during compiling. If you still don't get a
clue, send a message to the @uref{mailto:bug-gnubg@@gnu.org,,
@gnubg{}-mailinglist}.

@node @gnubg{} startup questions
@section @gnubg{} startup questions

@menu
* I get an error message when starting.::
* GNU Backgammon complains about missing files.::
* Starting from the @emph{WinXP} menu she plays like a beginner.::
* My screen mixes up while starting GNU Backgammon.::
* I only get a command-line interface. Where is the nice Board::
* When I restart GNU Backgammon all my settings are gone.::
* I do not need this graphical stuff. Where is the terminal for commands?::
@end menu

@node I get an error message when starting.
@subsection I get an error message when starting.

Well, your computer wants to communicate with you. Give him a chance and
read (and try to understand) what he is telling you. Then read the next
items carefully @enddots{} 

@node GNU Backgammon complains about missing files.
@subsection  GNU Backgammon complains about missing files.

GNU Backgammon is probably either missing the file @file{gnubg.weights}
or @file{gnubg.bd}. @file{Gnubg.bd} is the bearoff database that @gnubg{} uses to
evaluate endgame positions.

The file @file{gnubg.weights} contains the trained neural net weights
for most of @gnubg{}'s position evaluators.  Like @file{gnubg.bd}, it should
be kept in either the current directory or the installed directory.

@node Starting from the @emph{WinXP} menu she plays like a beginner.
@subsection Starting from the @emph{WinXP} menu she plays like a beginner.

Open the @emph{MS Windows} menu and go to the entry of
@gnubg{}. Right-click with the mouse and choose
@option{properties}. Check, if the @option{working path} is the same
directory as the @file{*.exe}-file one line above. If not, adjust the
working path.


@node My screen mixes up while starting GNU Backgammon.
@subsection My screen mixes up while starting GNU Backgammon.

Install the newest driver for your graphic card. Be sure that you have
chosen at least a desktop resolution of 65535 (16 bit colour depth). If
your card is a @emph{ATI Rage "somewhat"} there still might be some
problems with the graphical interface (GTK+)and @emph{MS Windows}.

@node I only get a command-line interface. Where is the nice Board
@subsection I only get a command-line interface. Where is the nice Board

Using @emph{MS Windows} just click on the correct menu entry (@option{GNU
Backgammon for windows}). If it still doesn't work, check whether
@file{c:\[path-to-your-gnubg]\gnubg.exe} exists or not.

@emph{GNU/Linux} users should check if @uref{http://www.gtk.org/,, GTK+} is
installed. 

@node When I restart GNU Backgammon all my settings are gone.
@subsection When I restart GNU Backgammon all my settings are gone.

Did you save your settings (menu @option{Settings, Save settings}) before? If
you have just installed a newer version of GNU Backgammon go to @ref{I
want to install a newer version.}

@node I do not need this graphical stuff. Where is the terminal for commands?
@subsection I do not need this graphical stuff. Where is the terminal for commands?

For @emph{GNU/Linux} users: open a terminal and start @gnubg{} with the
option @file{-t}.

@emph{MS Windows} users: Look for a file called @file{gnubg-no-gui.exe}
in @gnubg{}'s directory or open the @emph{MS Windows} menu
@option{execute} and type @file{c:\[path-to-your-gnubg]\gnubg-no-gui.exe}.
There is also a menu entry @option{GNU Backgammon Command Line Interface}.

@node Backgammon playing questions
@section Backgammon playing questions

@menu
* What is the difference of a new game or match or session?::
* What the heck is a beaver in Backgammon?::
* How do I move the checkers?::
* Why am I allowed to place more than 5 checkers on a spot?::
* GNU Backgammon plays poorly.::
* GNU Backgammon is to strong for me.::
* I think the bot is cheating. She always gets good dice.::
@end menu

@node What is the difference of a new game or match or session?
@subsection What is the difference of a new game or match or session?

When you start a new match you will be asked to play to a certain
amount of points (for example: 7 points). The player who firstly reaches
this amount wins the match.

Starting a new session means playing to an infinite amount. Be aware
that the rules do slightly differ then. You may break this session at
every point and save it.

If you choose to play a new game, GNU Backgammon will open the last
saved match or session you quit. When there is no saved match or session
you will start a new infinite session.


@node What the heck is a beaver in Backgammon?
@subsection  What the heck is a beaver in Backgammon?

A @emph{beaver} is only allowed in a moneygame session. To @emph{beaver}
means redoubling (and keeping the cube) directly after your opponent
doubled. For more information go to
@uref{http://www.bkgm.com/glossary.html#B,, Backgammon Galore (Glossary)}.

@node How do I move the checkers?
@subsection  How do I move the checkers?

The easiest way to move chequers is to @emph{"drag and drop."} Put your
mouse pointer to a chequer you want to move, press the left mouse button
and drag the chequer to the desired point (hold down the button while
dragging).

If you want to use mouse clicks you have to know, that the left mouse
button is for the left die shown on your board. Right click your mouse
for the right die.

For always getting the higher number on the left go to the menu
@option{Settings, Appearance, General} and activate @option{Show higher
die on left.}

@node Why am I allowed to place more than 5 checkers on a spot?
@subsection  Why am I allowed to place more than 5 checkers on a spot?

The official backgammon tournament rules allow to put all 15 chequers on a pip
(spot). If you want to play with a maximum of 5 chequers, go to the menu
@option{Settings} and activate the @option{Egyptian Rule.}

@node GNU Backgammon plays poorly.
@subsection  GNU Backgammon plays poorly.

Are you sure? If the answer is @emph{yes} you should think about going
to Monte Carlo this summer and win the Backgammon World Championship.

If this plan fails, check whether @file{gnubg.weights} is correctly
installed. See also @ref{GNU Backgammon complains about missing files.}

@node GNU Backgammon is to strong for me.
@subsection GNU Backgammon is to strong for me.

Go to the menu @option{Settings, Players} and change the values of
@option{Player 0}. There is also a set of predefined settings you may
choose from.

@node I think the bot is cheating. She always gets good dice.
@subsection I think the bot is cheating. She always gets good dice.

In the menu @option{Settings} you may choose between different random dice
generator. If you still think GNU Backgammon is cheating, program your
own dice generator or roll manually.

@node Settings questions
@section Settings questions

@menu 
* Where can I change the name of the human player?::
* How do I change the colours?::
* How do I stop the annoying beeps?"::
* What are "Plies?"::
* What is "noise?"::
* What is "reduced evaluation?"::
@end menu

@node Where can I change the name of the human player?
@subsection Where can I change the name of the human player?

Go to the menu @option{Settings, Players ...} and click on @option{Player
1}. At the top there is a field to change the human players name.

@node How do I change the colours?
@subsection How do I change the colours?
Go to the menu @option{Settings, Appearance}. Here you may change the colour
of chequers, the points and the board itself.

@node How do I stop the annoying beeps?"
@subsection How do I stop the annoying beeps?"

Go to the menu @option{Settings, Appearance} and click on the card
@option{General} at the right. Disable the option @option{Beep on illegal input}.

@node What are "Plies?"
@subsection What are "Plies?" 

A @emph{ply} describes how far GNU Backgammon evaluates  the
position. @emph{"0-ply"} means, GNU Backgammon estimates the worth of the
position as it is. A @emph{"1-ply"} evaluation looks one step
deeper. GNU Backgammon also evaluates positions that may occur one roll
further. @emph{"2-ply"} is another roll further and so on.

The more plies you choose the more you strengthen GNU Backgammon. But
keep in mind that it will also decrease her playing speed.

Note also that @emph{"0-ply"} in GNU Backgammon is equivalent to the
@emph{"1-ply"} evaluation of Snowie. 

@node What is "noise?"
@subsection What is "noise?"

Noise is nothing but kind of disturbing GNU Backgammons @ref{What are
"Plies?",, 0-ply} evaluation. Rising the noise decreases her playing
strength.

@node What is "reduced evaluation?"
@subsection What is "reduced evaluation?"

Reduced searches only work with 2-ply evaluations and deeper. It
somehow cuts the searching for candidates to increase speed.


@node Analysis questions
@section Analysis questions

@menu
* What are these funny letters at the right bottom?::
* How do I set up a position manually?::
* Which formats must I use to import positions?::
* Which formats must I use to import matches?::
* How can I switch the players sides?::
* What does "!" and "?" mean?::
* How is the error rate determined?::
@end menu

@node What are these funny letters at the right bottom?
@subsection What are these funny letters at the right bottom?

You will find two small windows titled @option{Position} and @option{Match
ID} at the bottom of the GNU Backgammon window. Here you may use the
@option{position_id}- or @option{match_id}-format for setting up or
copying positions.

An explanation of both formats will follow in GNU Backgammon's
documentation (hopefully soon).

@node How do I set up a position manually?
@subsection How do I set up a position manually?

Open a new game, match or session. If @gnubg{} already rolls the dice,
don't bother. Press @option{edit} and either type the @ref{What are these
funny letters at the right bottom?,, position_id} and press @kbd{Enter}
at your keyboard. Or use the mouse to set up the chequers.

A mouse click at the border of the board empties the pip. A left (right)
mouse click sets up a certain amount of chequers depending on where
exactly on the pip you click. Set up the cube with a right mouse click
on it. 

At last go to the menu @option{Game, Set turn} and choose the player on
roll. The dice will disappear then.

@node Which formats must I use to import positions?
@subsection Which formats must I use to import positions?

Currently only @file{*.pos} by @uref{http://jelly.effect.no/,,
Jellyfish} are supported.

@node Which formats must I use to import matches?
@subsection Which formats must I use to import matches?

You may import @file{*.mat} by @uref{http://jelly.effect.no/,,
Jellyfish} or @file{*.ssg} by @uref{http://www.gamesgrid.com/,,
Gamesgrid}. Also supported is the @emph{oldmove} format used on
@uref{http://www.fibs.com,, Fibs}. 

@node How can I switch the players sides?
@subsection How can I switch the players sides?

Go to the menu @option{Game and click on Swap players}.

@node What does "!" and "?" mean?
@subsection What does "!" and "?" mean?

After analysing a game or a match GNU Backgammon is able to do some
comments on chequer play or cube decisions. Open the menu @option{Window,
Game record} and you will see a list of the moves. If the actual  move or cube
decision differs from the best, GNU Backgammon will put a comment on it.

The default settings are:

@multitable @columnfractions .40 .30 .25 
@item +0.040 (very good): @tab  @emph{Not in use yet}
@item +0.020 (good):      @tab  @emph{Not in use yet}
@item -0.040 (doubtful):  @tab  @emph{?!}
@item -0.080 (bad):       @tab  @emph{?}
@item -0.160 (very bad):  @tab  @emph{??}
@end multitable

You may change these comment in the menu @option{Window, Annotation}
choosing another comment for moves and/or double.

@node How is the error rate determined?
@subsection How is the error rate determined?

GNU Backgammon determines the players strength as follows: If a player
has an average error (per move) of:

@multitable @columnfractions .40 .30 .25 
@item < 0.005 ---> @tab @emph{Extra-terrestrial}
@item < 0.010 ---> @tab @emph{World class}
@item < 0.015 ---> @tab @emph{Expert}
@item < 0.020 ---> @tab @emph{Advanced}
@item < 0.025 ---> @tab @emph{Intermediate}
@item < 0.030 ---> @tab @emph{Novice}
@item > 0.030 ---> @tab @emph{Beginner}
@end multitable

After analysing a game, match or session you can see the summary in the
menu @option{Analyse, @dots{} statistics}. Note that you can't change the
ranges of these values.

@node Database questions
@section Database questions

@menu
* What is the @option{Database} menu for?::
* "There are no target evaluations in the database to train from."::
* What is @option{Train with TD(0)}?::
@end menu

@node What is the @option{Database} menu for?
@subsection What is the @option{Database} menu for?

In the menu @option{Train, Generate database} GNU Backgammon will play
against herself (0-ply with @file{gnubg.weights}) generating a position
database. This database will be automatically saved as
@file{gnubg.gdbm} when you press the button @option{stop} at the left
side.

After the database is generated you may use @option{Train, Rollout
database} to do a 36-trial rollout of all positions. Then you may train
@file{gnubg.weights} with the new evaluated positions using
@option{Train, Train database}.


@node "There are no target evaluations in the database to train from."
@subsection "There are no target evaluations in the database to train from."

@ifnottex
You have forgotten to rollout the database before. See @ref{What is the
@option{Database} menu for?}.
@end ifnottex

@iftex
You have forgotten to rollout the database before. See @ref{What is the
Database menu for?}.
@end iftex



@node What is @option{Train with TD(0)}?
@subsection What is @option{Train with TD(0)}?

This will train the network by TD(0) using zero-knowledge self-play.



@node Abbreviations
@section Abbreviations

@menu
* "gwc"?::
* "mwc"?::
* "dp"?::
* "tg"?::
@end menu

@node "gwc"?
@subsection "gwc"?

"gwc" is an abbreviation for @emph{game winning chances}. 

@node "mwc"?
@subsection "mwc"?

"mwc" is an abbreviation for @emph{match winning chances}.

@node "dp"?
@subsection "dp"?

In the menu @option{Analyse, Game/Match/Session statistics} you will see
a window with some statistics. Near the bottom you'll see four lines
beginning with @option{Missed @dots{} and Wrong @dots{}}.  "dp" means "doubling
point" and describes a situation in the game, where you probably should have
doubled your opponent.

@node "tg"?
@subsection "tg"?

"tg" is an abbreviation for "too good". It points to  a situation in the
game, where you probably should have kept the cube (mostly because of
huge gammon chances) rather than doubling out your opponent. 
