\input texinfo
@setfilename gnubg.info
@settitle GNU Backgammon
@include version.texi

@set month-year October, 2003

@syncodeindex vr cp

@macro gnubg
@t{gnubg}
@end macro

@dircategory Games
@direntry
* gnubg: (gnubg).               GNU Backgammon.
@end direntry

@ifinfo
This file documents GNU Backgammon, a program for playing and analysing
backgammon games and matches.

Copyright @copyright{} 1999, 2000, 2001, 2002 Gary Wong, Achim Mueller.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1; with
no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled "GNU Free
Documentation License".
@end ifinfo

@titlepage
@sp 10
@title GNU Backgammon
@subtitle version @value{VERSION}
@subtitle @value{month-year}
@author Gary Wong, Achim Mueller
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999, 2000, 2001, 2002 Gary Wong, Achim Mueller

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1; with
no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
copy of the license is included in the section entitled "GNU Free
Documentation License".
@end titlepage

@ifnottex
@node Top
@top GNU Backgammon

This manual describes how to use GNU Backgammon to play and analyse
backgammon games and matches.  It corresponds to version @value{VERSION}
(updated in @value{month-year}).

@menu
* Introduction::			What is GNU Backgammon.
* For the impatient::			A short description how to use GNU Backgammon.
* How to play backgammon::		The rules of the game.
* Installing the software::		How to install GNU Backgammon under MS Windows, FreeBSD and Linux.
* Starting GNU Backgammon::		Starting the software using a terminal and the graphical user interface (GUI)
* Playing backgammon::			How to play a game, match or session.
* Saving games::			How to save your positions, games, matches and sessions.
* Opening files::			How to open saved positions, games, matches and sessions.
* Import files::			Opening files from different formats.
* Export files::			Saving files into different formats.
* Settings::				Changing settings in GNU Backgammon.
* Analysis and rollouts::		How to analyse positions, games, matches or sessions.
* Position and match IDs::		A brief technical explanation.
* Cubeful equities::                    How do @gnubg{} calculate cubeful equities.
* Training::				How to store databases and train the neural nets.
* Scripting::                           How to use @gnubg{} python scripting.
* Bearoff databases::                   How to generate bearoff databases for use with GNU Backgammon
* Absolute ratings::                    How are the absolute ratings derived
* Additional documentation::            Links to other documentation regarding backgammon or GNU Backgammon 
* GNU Free Documentation License::	Your rights regarding this manual.
* Command Index::                       Index of available commands
* Concept Index::                       Index
@end menu
@end ifnottex

@node Introduction
@chapter Introduction
@include intro.texi

@node For the impatient
@chapter For the impatient
@include impatient.texi

@node How to play backgammon
@chapter How to play backgammon
@include rules.texi

@node Installing the software
@chapter Installing the software
@include install.texi

@node Starting GNU Backgammon
@chapter Starting GNU Backgammon
@include starting.texi

@node Playing backgammon
@chapter Playing backgammon
@include playing.texi

@node Saving games
@chapter Saving games
@include saving.texi

@node Opening files
@chapter Opening files
@include opening.texi

@node Import files
@chapter Import files
@include import.texi

@node Export files
@chapter Export files
@include export.texi

@node Settings
@chapter Settings
@include settings.texi

@node Analysis and rollouts
@chapter Analysing and rollouts
@include analyse.texi

@node Position and match IDs
@chapter Position and match IDs
@include id.texi

@node Cubeful equities
@chapter Cubeful equities
@include cubeful.texi

@node Training
@chapter Training
@include training.texi

@node Scripting
@chapter Scripting
@include scripting.texi

@node Bearoff databases
@chapter Bearoff databases
@include bearoff.texi

@node Absolute ratings
@chapter Absolute ratings
@include absrating.texi

@node Additional documentation
@chapter Additional documentation
@include additional.texi

@node GNU Free Documentation License
@unnumbered GNU Free Documentation License
@include fdl.texi

@node Command Index
@unnumbered Command Index
@printindex ky

@node Concept Index
@unnumbered Index
@printindex cp

@bye
