
@menu
* Opening a game::
* Opening a match::
* Opening a session::
* Opening a position::
@end menu

@node Opening a game
@section Opening a game

@node Opening a match
@section Opening a match

@node Opening a session
@section Opening a session

@node Opening a position
@section Opening a position


